#
# Makefile
#
# Board functions for TI AM3352 EISSBox3 board
#
# Copyright (C) 2018, IPKeys Technologies, LLC - http://www.ipkeys.com/
#

ifeq ($(CONFIG_SKIP_LOWLEVEL_INIT),)
obj-y	:= mux.o
endif

obj-y	+= board.o
